### ISSUE TITLE
 ErrorException: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated

### ISSUE THREAD

**Issue by lazysteve2020** [php-webdriver/php-webdriver#1070]
### Bug description

 ErrorException: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated
php-webdriver\webdriver\lib\Remote\HttpCommandExecutor.php:207

### How could the issue be reproduced

```shell
$command = new WebDriverCommand(
      null,
      DriverCommand::NEW_SESSION,
      array('desiredCapabilities' => $desired_capabilities)
    );


   $command = new WebDriverCommand(
      '',
      DriverCommand::NEW_SESSION,
      array('desiredCapabilities' => $desired_capabilities)
    );
```

### Expected behavior

 ErrorException: str_replace(): Passing null to parameter #2 ($replace) of type array|string is deprecated
php-webdriver\webdriver\lib\Remote\HttpCommandExecutor.php:207

### Php-webdriver version

115.0.5790.102

### PHP version

8.1.21

### How do you start the browser driver or Selenium server

driver

**Comment by OndraM** [comment]
Hi, this was fixed in php-webdriver 1.12.0, released on 2021-10-14, so it seems you are using an old version of php-webdriver.

You can find out the current version running
`composer show php-webdriver/webdriver` and look for the "Version" field.

Please run `composer update` to get the latest version (1.14.0 or newer).

In case the issue persist with the latest version, please open a new issue.

Thank you!
