### ISSUE TITLE
[RFC] Replace internal webdriver client with a generated one (full async compatible)

### ISSUE THREAD

**Issue by joelwurtz** [php-webdriver/php-webdriver#558]
Hi,

First of all, thank you for this lib and the time you spent on it.

I'm one of the maintainer of https://github.com/jolicode/asynit, which is an async first testing runner, and we would really love to have webdriver supports.

Unfortunately none of the existing library have async support, that's why i began to write https://github.com/joelwurtz/async-webdriver, which is a generated client for the webdriver specification, all of the generated code comes from the OpenAPI specification written here : https://github.com/joelwurtz/async-webdriver/blob/master/openapi-spec.json

This generated client allow to support async (by using https://amphp.org/ libraries) and sync client (it uses PSR7 and will be compatible with the PSR18, if it's ever a thing)

However, after discussing this with @dunglas , i think that instead of having too many differents librairies on webdriver, we could work together to integrate this generated client as the low level API client in a future major version.

Main challenge would be to branch existing interfaces to this generated client, but i think it's worth the pain as having a generated client here will reduce a lot the maintenance effort. (As an exemple i use the same approach on https://github.com/docker-php/docker-php and i'm able to follow up docker api changes: new spec every month)

So here is my proposal:

 * Use a generated client for the low level api of webdriver (by using https://github.com/janephp/open-api)
 * Only supports the new WebDriver specification in this client (for #469)
 * Branch existing interfaces to use this low level api for less BC breaks and also because they are efficient.
 * Adding support for async on every existing interface, unfortunately every async call need to return a promise which is not compatible with current interfaces.

**Comment by OndraM** [comment]
Hi @joelwurtz,
this is an interesting idea and I generally like it - the W3C support will require some internal refactoring no matter what, so now its a perfect time to consider such thing :). However doing this could have many consequences and could widely affect users of this library, so this must be considered really carefully. From a quick look, I have a few points and questions regarding this:
- First of all, its a great effort of yours, mapping W3C spec to OpenAPI! I have a quick look and it look nice, though few things diverts from the W3C spec (ie. `SessionCapabilities` should be called just `Capabilities` etc.). But haven't you think as bringing this to Selenium project itself? It may be interesting for them to have "official" OpenAPI definition of WebDriver as well. Also the api spec is not PHP-specific and could be used by various implementations. You can try reach them on IRC `#selenium`, especially look for David Burns and Simon Stewart, editors of the W3C spec itself.
- php-webdriver is meant as a low-level library itself, the generated client has IMO really big dependency tree footprint: php-webdriver has now **one** composer no-dev dependency, this would add **32 more**. But I guess this is because of the process of generating the client and could be solvable by splitting the generated classes to standalone package or by moving the libraries required for parsing the OpenAPI json to dev-dependencies, right?
- Implementing only W3C protocol is currently unfortunately not an option... I considered this as well, but as of now, only GeckoDriver and IEDriverServer fully supports W3C WebDriver, while eg. ChromeDriver is still [far from being there](https://chromium.googlesource.com/chromium/src/+/master/docs/chromedriver_status.md). So removing OSS protocol completely would effectively cut ChromeDriver users from this library. So implementing an adapter and protocol negotiation is still the preferred (and from my point of view required) way to go.
- Just a sidenote - public API of this library is based on official Java language client. While it doesn't have to be followed 1:1 (and it already isn't), I think the main concept should be kept. Also bringing some BC breaks looks now as inevitable, but it should be as few as possible.
- I plan to invest some time in bringing W3C protocol support (#469) to php-webdriver, but in case all these issues could be solved and we decide to go this way, would you be interested in this effort as well?

**Comment by joelwurtz** [comment]
> But haven't you think as bringing this to Selenium project itself? It may be interesting for them to have an "official" OpenAPI definition of WebDriver protocol as well. Also the api spec is not PHP-specific and could be used by various implementations.

Yes, this would be the goal. 

However, this specifiation is on the 2.0 version of OpenAPI (not the current 3.0 spec), and since we are in a transition period (3.0 is the officially supported spec ATM, but a lot of projects and existing tools only support the 2.0 version) i don't think this is the right time to do this.

Futhermore, this spec is far from being complete and would like to have something with a better coverage.

> php-webdriver is meant as a low-level library itself and some really popular projects uses this (Codeception, Dusk to name few), but the generated client has IMO really big dependency tree footprint and could be unacceptable for these frameworks: php-webdriver has now one composer no-dev dependency, but this would add 32 more. However I guess this is partly because of the process of generating the client and could be solvable by splitting the generated classes to standalone package or by moving the libraries required for parsing the OpenAPI json to dev-dependencies, right?

I can understand this, ATM the async webdriver require amphp/aerys (as it's async). But in this lib async could be optional so this would remove a lot of dependencies.

Also libraries required for parsing / generating the code are already in the dev section, jane (the tool generating the client) propose a parsing / generating package which should be in the dev section and a runtime package that provides code and dependencies to use the generated code.

Dependencies on the generated code are : 

  * PSR7 (so user will need an implementation or this lib can provide one directly in the deps)
  * HTTPlug (Future PSR18), like psr7 user will need an implementation (or this lib can provide one)
  * php-http/message-factory : which allow to have a common interface for creating request / response for each psr7 implementation
  * Some common tools around HTTPlug (plugins system, which allow stuff like logging / profiling / host switching for end user)
  * symfony/options-resolver : used to validate parameters passed to the query / form / headers parameter given the specification

In final it will be more from 7 to 10 dependencies rather than 32, but it might still be a lot for some libraries, however thoses dependencies began to be pretty common in a lot of libraries (psr7 and httplug are widely used and symfony/options-resolver not sure i need to talk about since it's one of the most used php package)

However it might be possible to reduce this number of dependencies (i'm the author of jane so ...). As you are not the first that is "afraid" of having this many dependencies, despite i'm don't agree with it this a recurrent concern and i have some ideas to reduce it.

> Implementing only W3C protocol is currently unfortunately not an option... I considered this as well, but as of now, only GeckoDriver and IEDriverServer fully supports W3C WebDriver, while eg. ChromeDriver is still far from being there. So removing OSS protocol completely would effectively cut ChromeDriver users from this library. So implementing an adapter and protocol negotiation is still the preferred (and from my point of view required) way to go.

Didn't know about that. but it would be possible to also generate old endpoints (with a second specification by example). Please note that Jane is able to generate multiple API Clients in one go. Which means we can have two separate API that can share some models without having duplicate code. We can then implement a protocol negotiation on top of it.

> Just a sidenote - public API of this library is based on official Java language client. While it doesn't have to be followed 1:1 (and it already isn't), I think the main concept should be kept. Also bringing some BC breaks looks now as inevitable, but it should be as few as possible.

Totally agree

> I plan to invest some time in bringing W3C protocol support (#469) to php-webdriver, but in case all these issues above could be solved and we decide to go this way, would you be interested in this effort as well?

I'm really interested in the async part :) so if this is a wanted feature for the next version of this lib i will gladly take effort in it. As i really believe having async in a lib like this is a game changer.

**Comment by OndraM** [comment]
@joelwurtz Thanks for the reply. I have some notes regarding you reply, but in the meantime it may be interesting to have also an opinion from someone using php-webdriver as part of other project - and Codeception came on my mind. So lets bring this to @DavertMik - what do you think?

**Comment by DavertMik** [comment]
> Unfortunately none of the existing library have async support

My first question is what do you plan to achieve by introducing async support for webdriver? From my experience maintaining CodeceptJS (where I work with 2 webdriver implementations) async is a pain for testing and libraries do whatever they can to reduce the need to deal with it. Webdriverio uses fibers, SeleniumWebdriverJS used ControlFlow. There are no real benefits you can get with async webdriver client because you run synchronous browser session, I heard no argument for it while talking with JS community. 

But I agree of taking php-webdriver towards new protocol. And OpenAPI stuff seems pretty interesting to get with, and code generation is a really smart approach. If we could introduce this part into php-webdriver witout BC that would be really nice

**Comment by joelwurtz** [comment]
Creating multiple sessions and working on them in parallel does not work ? If you have multiple test scenario you could excute them in "parallel" over multiple sessions so having this would allow faster test execution (and still allow having dependencies between scenario)

**Comment by joelwurtz** [comment]
Has for the testing part, this is mainly for this library https://github.com/jolicode/asynit where testing async is not a pain

**Comment by DavertMik** [comment]
@joelwurtz yes, there is a good sense for async in case of HTTP testing. So asynit looks really nice.

But in case of webdriver you will get more problems than profit by implementing async approach. 

> Creating multiple sessions and working on them in parallel does not work ? 

Technically you can do it. Practically if you need to run tests in parallel you can just execute them via multiple PHP scripts with the same benefit and no extra code change. Writing async code for webdriver is hard because each webdriver call is asynchronous and all your test consists only of calling webdriver API. So you get test full of `await` (or `yield`) in your case. So what if a developer forgets to add yield for one call? They will get a problem.  Anyway, this introduces unnecessary complexity for such tests.

Also, the next problem is logging and debugging such tests. In Codeception we print test execution step by step but in case you run multiple browsers you will get a total mess as an output result.

---
So the overall conclusion would be: it's really nice that we can write our webdriver tests synchronously in PHP. If we get to limit where tests go slow we should run them in separate scripts instead of rewriting the code to async.

**Comment by joelwurtz** [comment]
> Technically you can do it. Practically if you need to run tests in parallel you can just execute them via multiple PHP scripts with the same benefit and no extra code change

Not really, when you have dependencies between test it's really hard to split them into differents scripts because at some point you need to sync results and even use data from previous test, asynit allow you to do that, as an exemple you can have two scenarios depending on another one, when the dependency is resolved you can execute those 2 scenrarios in parallel with the data coming from the dependency.

> So you get test full of await (or yield) in your case. So what if a developer forgets to add yield for one call? They will get a problem. Anyway, this introduces unnecessary complexity for such tests.

Then it will throw an error because if you forget the await / yield keyword you have a Promise that does not have the api that you want to use (so you will certainly get a bad method call exception)

But i agree, with you not every developer is used to do async in PHP, even more with the `yield` keyword (most use ReactPHP and event system). 
However like i said, if we ever do this here, it will be optional, and sync will still be the first class citizen strategy (so Codeception will not have to be rewritten in async).

Futhermore if we use jane as the low level api code generator, async is only one option to add to the generator, and a lot of code can be mutualised.

 > Also, the next problem is logging and debugging such tests. In Codeception we print test execution step by step but in case you run multiple browsers you will get a total mess as an output result.

I 100% agree with you this is one of my big problem actually, i have done some formatter that are able to go back into the console and rewrite a line, but overall it was not very usable (so ATM i only print when test is finished). I have some ideas in mind (one of them would be to have a lib like https://github.com/chjj/blessed and use advanced interface in terminal) but no real clean solution.

**Comment by joelwurtz** [comment]
From what i have seen (but i'm not used to this library, so i may be wrong), HttpCommandExecutor and DriverCommand would no longer be needed, and every class using them would need to use the generated client instead (or a custom wrapper to support JsonWire protocol)

As an exemple https://github.com/facebook/php-webdriver/blob/community/lib/Remote/RemoteWebDriver.php would no longer have the HttpCommandExecutor injected but the Client generated instead

**Comment by matheusfaustino** [comment]
Another benefit that I saw, that is not just for testing, is the possibility of using it in a crawler framework, for instance Scrapy from python, you make async requests using the webdriver without blocking the whole queue of requests as it happens with scrapy, for exemple.

**Comment by OndraM** [comment]
We coincidentally chatted about OpenAPI specs for W3C protocol with @christian-bromann - he started to write the OpenAPI specs himself: https://github.com/webdriver/webdriver/tree/master/openapi

While I don't think we should do this for php-webdriver 2.0 (there are already lots of other things, see #657), we cen return to this later and maybe eventually replace the http layer of php-webdriver with one which is generated from the OpenAPI using eg. https://github.com/janephp/open-api (and doing this without API changes to end-users to maintain BC).

**Comment by OndraM** [comment]
Closing this for now, however the general idea is not bad, we can return to it later.
