### ISSUE TITLE
Screenshot are not fullscreen!

### ISSUE THREAD

**Issue by Mr3RF** [php-webdriver/php-webdriver#659]
![IMG_20190816_114003_856](https://user-images.githubusercontent.com/54153824/63150667-addbef00-c01c-11e9-94cf-3c00d802401a.jpg)
When I Use takeScreenShot Method The Output Will Be Something Like That! It Will Screenshot Top Left Corner Of The Page Not The Full Page!

**Comment by andrewnicols** [comment]
Can you please provide full replication instructions, including the script used. There is not enough information and this issue will be closed without the relevant information.

**Comment by OndraM** [comment]
I think fullscreen screenshot is not part of W3C WebDriver.

However Firefox include its proprietary endpoint to take fullscreen screenshot, it could be used like this:
```
$screenshot = $driver->executeCustomCommand(
    '/session/:sessionId/moz/screenshot/full/',
    'POST'
);
file_put_contents('full.png', base64_decode($screenshot));
```

In Chrome it may be also possible to do via DevTools protocol (it requires #556), because Chrome has this implemented internally, but I'm not sure it has exposed WebDriver endpoint for this.
