### ISSUE TITLE
composer is stupid! I dont want to comment about it's developers!

### ISSUE THREAD

**Issue by Shamim1977** [php-webdriver/php-webdriver#766]
Anybody has an installed copy of php-webdriver? I needed 1.8.
Please help if u can.

**Comment by OndraM** [comment]
No, Composer is actualy done by great dedicated developers.

If you have any issue with php-webdriver, please post the error here.

Also make sure you've read [Upgrade from version <1.8.0](https://github.com/php-webdriver/php-webdriver#upgrade-from-version-180) in readme before you blame others.

**Comment by Shamim1977** [comment]
You didnt even get my point and closed the topic!! ...What a productive brain!!

**Comment by OndraM** [comment]
@Shamim1977 You didn't provide any clue what is the issue you are having. You also didn't used the issue template which was provided to you when you created the issue. However you without any respect blamed other people, so you cannot expect any help with this behavior.

If you'd like to install php-webdriver, follow steps described in [readme](https://github.com/php-webdriver/php-webdriver#installation). If you encounter an error, please try to use Google to find the answer first. If it don't help, please submit a new issue, where you describe the whole issue and provide logs, error messages and command you used etc., so that we can help you.
