### ISSUE TITLE
php-webdriver should include composer conflict to facebook/webdriver

### ISSUE THREAD

**Issue by FritsvanCampen** [php-webdriver/php-webdriver#780]
### What are you trying to achieve? (Expected behavior)
Update my private packages to `php-webdriver/webdriver` (from `facebook/webdriver`).

### What do you get instead? (Actual behavior)
Composer explodes:
```PHP Fatal error:  Cannot declare class Facebook\WebDriver\...```
Depending on the order of commands and compatibility of sub-dependencies.

### How could the issue be reproduced? (Steps to reproduce)
Have a project with a (sub-)dependency to both `facebook/webdriver` and `php-webdriver/webdriver`.

### Details
* Php-webdriver version: 1.8.2 (latest)

### Suggested fix
Include:
```
    "conflict": {
        "facebook/webdriver": "*"
    },
```
in `composer.json`/`package.json`

**Comment by OndraM** [comment]
I believe we can even use "replace", not "conflict". 

In case of "replace" this package will fulfill subdependency to facebook/webdriver, so that no conflict will happen. We can do this because the whole repository was forked, tags were copied and we made no BC breaks, so this could serve as drop-in replacement even for subdependencies.

See #785.
