### ISSUE TITLE
FAIL: ChromeOptions->setBinary('/usr/bin/chromedriver')

### ISSUE THREAD

**Issue by corbolais** [php-webdriver/php-webdriver#855]
Setting the chromedriver binary path via 

https://github.com/php-webdriver/php-webdriver/blob/af21de3ae5306a8ca0bcc02a19735dadc43e83f3/lib/Chrome/ChromeOptions.php#L55

and then calling

    Chromedriver::start($this->opts->setBinary($this->chromedriverBin)->toCapabilities());

Fails with

    PHP Fatal error:  Uncaught Exception: '' is not a file. in vendor/php-webdriver/webdriver/lib/Remote/Service/DriverService.php:120

As ChromeDriverService is only checking for a environment variable:

https://github.com/php-webdriver/php-webdriver/blob/af21de3ae5306a8ca0bcc02a19735dadc43e83f3/lib/Chrome/ChromeDriverService.php#L27

And expectedly so this does work:

    putenv('WEBDRIVER_CHROME_DRIVER=' . $this->chromedriverBin);

Any comments?

cheers

**Comment by andrewnicols** [comment]
Hi @corbolais ,

Can you please answer the questions provided in the New Bug Report template (https://github.com/php-webdriver/php-webdriver/issues/new?assignees=&labels=bug&template=bug_report.md&title=).

@OndraM, what's the intent of the ChromeDriverService? I typically just instantiate against a given WD URL and have never used it.

**Comment by OndraM** [comment]
Well is `ChromeDriverService` extends `DriverService`, so its responsible to for creating instance of local webdriver, ie. it starts the browser-driver binary and manages it state. So that you don't need to start it yourselves. Its best suitable for simple local running of one test at a time. 

About this issue by @corbolais - I see multiple problems:

a) Chromedriver does not know location of the chromedriver binary. It simply must be set in `WEBDRIVER_CHROME_DRIVER` environment variable, [see wiki](https://github.com/php-webdriver/php-webdriver/wiki/Chrome#start-directly-using-chromedriver-class).
b) Parameter of `setBinary()` should be used when you need to specify path to chrome in non-standard location (see [chromedriver docs](https://chromedriver.chromium.org/capabilities#TOC-Using-a-Chrome-executable-in-a-non-standard-location)), not path to chromedriver. So you should usually not be using this if you don't have multiple versions of chrome installed.
c) `ChromeDriverService` was recently updated, and according to the error, it is not from the last version of php-webdriver, so I suggest running `composer update`.

**Comment by wyman101** [comment]
how did you solve this issue? i'm getting the same '' is not a file even when doing this:
`putenv('WEBDRIVER_CHROME_DRIVER=/usr/local/bin/chromedriver'`);

**Comment by corbolais** [comment]
> how did you solve this issue? i'm getting the same '' is not a file even when doing this: `putenv('WEBDRIVER_CHROME_DRIVER=/usr/local/bin/chromedriver'`);

First off: double-check this file '/usr/local/bin/chromedriver' in fact exists on the machine producing this error.

Then, @OndraM put it quite comprehensively: 

1. Use, `WEBDRIVER_CHROME_DRIVER` to specify the path to the `ChromeDriver` binary, 
2. Use setBinary() to specify the path to google chrome binary and 
3. lastly, make sure to have `ChromeDriverService` updated.

This should do it. In any case, I haven't looked at ChromeDriver in a long time. It's more than likely someone else can provide you with more recent details on this.

HTH
