### ISSUE TITLE
Proxy auth from example page

### ISSUE THREAD

**Issue by fissben** [php-webdriver/php-webdriver#884]
Couldn't manage to use a proxy with example from here README.md [(this)](https://github.com/php-webdriver/php-webdriver/wiki/HowTo-Work-with-proxy)

Selenium constantly logging error like this:
`Response code 400. Message: httpProxy is not of the form host[:port]: cleared_user:cleared_password@cleared_ip:cleared_port`

Which is fair enough according to java doc [here](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/Proxy.html#setHttpProxy(java.lang.String))

Is there any other option to use http proxy with authorization ?

BR, DK

**Comment by fissben** [comment]
What i've also tried(with no luck):
```php
use Facebook\WebDriver\Firefox\FirefoxDriver;
use Facebook\WebDriver\Firefox\FirefoxPreferences;
use Facebook\WebDriver\Firefox\FirefoxProfile;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;

$profile = new FirefoxProfile();

$profile->setPreference('network.proxy.type', 1);
$profile->setPreference('network.proxy.http', "ip");
$profile->setPreference('network.proxy.http_port',"port");
$profile->setPreference("network.proxy.username", "user");
$profile->setPreference("network.proxy.password", "pass");


$caps = DesiredCapabilities::firefox();
$caps->setCapability(   WebDriverCapabilityType::PROXY, [

    'proxyType' => 'manual',
    'httpProxy' =>  $proxyUrl,
    'sslProxy' =>   $proxyUrl,
]);

$caps->setCapability( FirefoxDriver::PROFILE, $profile);

```

**Comment by OndraM** [comment]
Hi,
thanks for reporting the issue, but it seems you didn't use the default issue template provided when creating a new issue. 

Issue templates help this project to stay in shape - please use them and fill them out completely. By doing that you are helping the project because the community and maintainers can provide prompt feedback, and potentially solve the issue, which is almost impossible without the information in the template.

If you are not reporting a bug but rather asking a question or looking for help, you can use our [Discussions](https://github.com/php-webdriver/php-webdriver/discussions).

If you think this is incorrect, please feel free to open a new issue and provide the information required in the template.

Thanks for your understanding
